# Pattern Shop — developer tasks
#
# `DOCKER` defaults to `docker`. If your Docker CLI is not on PATH (e.g. a
# non-interactive shell with Rancher Desktop), override it, e.g.
#   make infra-up DOCKER="$HOME/.rd/bin/docker"
#
# Local `.env` (generated by `make env`) is loaded so targets can use variables
# like $(MYSQL_ROOT_PASSWORD).

SHELL := /bin/sh

-include .env
export

DOCKER ?= docker
COMPOSE ?= $(DOCKER) compose
CARGO ?= cargo
TEST_DATABASE_URL = mysql://root:$(MYSQL_ROOT_PASSWORD)@127.0.0.1:3306/user_service

.PHONY: help env hooks check up down build logs clean \
        infra-up infra-down dev dev-user dev-messenger \
        test test-unit test-integration test-e2e \
        mysql-up wait-mysql wait-kafka wait-services

help:
	@echo "Setup:"
	@echo "  env           Generate a local .env with random DB credentials"
	@echo "  hooks         Install the git pre-commit hook (.githooks)"
	@echo ""
	@echo "Run the stack:"
	@echo "  up            Build + start the whole stack in Docker (detached)"
	@echo "  down          Stop and remove containers + volumes"
	@echo "  infra-up      Start infra only (mysql, kafka, mailpit) for local dev"
	@echo "  infra-down    Stop infra containers (keeps the DB volume)"
	@echo "  dev           Run both services with cargo against the infra (Ctrl-C stops)"
	@echo "  dev-user      Run only user-service with cargo"
	@echo "  dev-messenger Run only messenger-service with cargo"
	@echo "  logs          Follow stack logs"
	@echo ""
	@echo "Quality / test:"
	@echo "  check             fmt --check + clippy -D warnings + no-unwrap gate"
	@echo "  test-unit         unit tests (no services)"
	@echo "  test-integration  start MySQL, run workspace integration tests"
	@echo "  test-e2e          start the stack, run the e2e crate"
	@echo "  test              unit + integration + e2e"

# --- setup -----------------------------------------------------------------

env:
	bash scripts/init-env.sh

.env:
	bash scripts/init-env.sh

hooks:
	git config core.hooksPath .githooks
	@echo "installed pre-commit hook (.githooks/pre-commit)"

check:
	$(CARGO) fmt --all --check
	$(CARGO) clippy --workspace --all-targets -- -D warnings
	bash scripts/check-unwrap.sh

# --- full stack (Docker) ---------------------------------------------------

up: .env
	$(COMPOSE) up --build -d

down:
	$(COMPOSE) down -v

build:
	$(COMPOSE) build

logs:
	$(COMPOSE) logs -f

clean:
	$(CARGO) clean

# --- local dev: infra in Docker, services with cargo -----------------------

infra-up: .env
	$(COMPOSE) up -d mysql kafka mailpit
	$(MAKE) wait-mysql wait-kafka

infra-down:
	$(COMPOSE) stop mysql kafka mailpit

dev: .env
	bash scripts/dev.sh

dev-user:
	$(CARGO) run -p user-service

dev-messenger:
	$(CARGO) run -p messenger-service

# --- tests -----------------------------------------------------------------

test: test-unit test-integration test-e2e

test-unit:
	$(CARGO) test --workspace --lib

# Integration tests need MySQL only; #[sqlx::test] creates throwaway databases,
# so they must connect as root.
test-integration: mysql-up wait-mysql
	DATABASE_URL="$(TEST_DATABASE_URL)" $(CARGO) test --workspace --tests

# E2E tests need the full stack (both services + MySQL + Kafka + mailpit).
test-e2e: .env
	$(COMPOSE) up --build -d
	$(MAKE) wait-services
	E2E_DATABASE_URL="mysql://root:$(MYSQL_ROOT_PASSWORD)@127.0.0.1:3306/messenger_service" \
		$(CARGO) test -p e2e -- --ignored --test-threads=1

# --- helpers ---------------------------------------------------------------

mysql-up: .env
	$(COMPOSE) up -d mysql

wait-mysql:
	@printf "waiting for mysql"; \
	until [ "$$($(COMPOSE) ps -q mysql | xargs $(DOCKER) inspect -f '{{.State.Health.Status}}' 2>/dev/null)" = "healthy" ]; do \
		printf "."; sleep 1; \
	done; echo " ok"

wait-kafka:
	@printf "waiting for kafka"; \
	until [ "$$($(COMPOSE) ps -q kafka | xargs $(DOCKER) inspect -f '{{.State.Health.Status}}' 2>/dev/null)" = "healthy" ]; do \
		printf "."; sleep 1; \
	done; echo " ok"

wait-services:
	@printf "waiting for services"; \
	until curl -fsS http://localhost:3030/health >/dev/null 2>&1 \
	   && curl -fsS http://localhost:3031/health >/dev/null 2>&1; do \
		printf "."; sleep 1; \
	done; echo " ok"
