#!/usr/bin/env bash
# Generate a local `.env` with random database credentials.
# Run once after cloning: `make env` (or `bash scripts/init-env.sh`).
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then
    echo ".env already exists — leaving it untouched"
    exit 0
fi

gen() { openssl rand -hex 24; }

root_pw=$(gen)
user_pw=$(gen)
messenger_pw=$(gen)

umask 077
cat > .env <<EOF
# Generated by scripts/init-env.sh — git-ignored, do not commit.

# --- MySQL credentials (generated per machine) ---
MYSQL_ROOT_PASSWORD=$root_pw
USER_SVC_PASSWORD=$user_pw
MESSENGER_SVC_PASSWORD=$messenger_pw

# --- host runs of the services (cargo run / debugging) ---
DATABASE_URL=mysql://user_svc:$user_pw@127.0.0.1:3306/user_service
MESSENGER_DATABASE_URL=mysql://messenger_svc:$messenger_pw@127.0.0.1:3306/messenger_service
KAFKA_BROKERS=localhost:29092
SMTP_HOST=localhost
SMTP_PORT=1025

# --- user-service ---
SERVICE_PORT=3030
OTP_TTL_MINUTES=120
SESSION_TTL_MINUTES=10080
SESSION_CLEANUP_INTERVAL_SECONDS=3600
OUTBOX_POLL_MS=1000

# --- messenger-service ---
MESSENGER_PORT=3031
SMTP_FROM=no-reply@pattern-shop.local
SENDGRID_API_KEY=
SENDGRID_BASE_URL=https://api.sendgrid.com

# --- logging ---
RUST_LOG=info
EOF

echo ".env created with generated credentials"
